gazebo_ros_control/pid_gains:
  base_link_to_prismatic_x: {p: 1.0, i: 1.0, d: 0.0}
  prismatic_x_to_prismatic_y: {p: 1.0, i: 1.0, d: 0.0}
  prismatic_y_to_prismatic_z: {p: 1.0, i: 1.0, d: 0.0}
  prismatic_z_to_revolute_x: {p: 1.0, i: 1.0, d: 0.0}
  revolute_x_to_revolute_y: {p: 1.0, i: 1.0, d: 0.0}
  revolute_y_to_revolute_z: {p: 1.0, i: 1.0, d: 0.0}


